config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :categories, only: %w[show index]
  resources :posts
  root 'pages#index' ,as: 'home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
end

app/models/character.rb
class Character < ApplicationRecord
    belongs_to :post
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/machine.rb
class Machine < ApplicationRecord
    has_many : machine_characters
    belongs_to :category
    belongs_to :user
end

app/models/machine_character.rb
class MachineCharacter < ApplicationRecord
    belongs_to :machine
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :characters
    belongs_to :category
    belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :posts
         has_many :machines
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @heading = 'Станки'
    #@categories=Category.all
  end
  def machine
    @machines=Machine.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    def index
        @posts = Post.all
    end
    def new
    end
    def show
        @post=Post.find(params[:id])
    end
    def create
       # render plain: params[:post].inspect
       @post = current_user.posts.build(post_params)
       @post.save
       redirect_to @post
    end
    private def post_params
        params.require(:post).permit(:name, :desc, :category_id, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user=current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Engie</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-light bg-none">
        <%= link_to home_path do %> <img class="logo" src="/engie_logo.png"><%end%>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%= link_to new_post_path, class:"btn navbar-btn" do %> <span class="nav-link" >New post </span><%end%>
            <%= link_to home_path, class:"btn navbar-btn" do %> <span class="nav-link" >Home </span><%end%>
            <%= link_to posts_path, class:"btn navbar-btn" do %> <span class="nav-link" >Posts </span><%end%>
          </div>
        </div>
        <div class="container index-form">
          <% if user_signed_in? %>
            <div class="greetings"><span><label for='exit'>Здравствуйте, <%= current_user.email %></label></span><br>
              <%= link_to 'Выйти', destroy_user_session_path, :method => :delete, class:'exit-btn index-btn', name: 'exit'%>
            </div>
          <% else %>
            <div class="enter">
              <%= link_to 'Войти', new_user_session_path, class:"log-in-btn index-btn" %> или <%= link_to 'Зарегистрироваться', new_user_registration_path, class:" register-btn index-btn" %>
            </div>
          <% end %>
        </div>
      </nav>
    </header>
    <div class="container main">
      <%= yield %>
    </div>
    <footer class="page-footer">
      <div class="container">
        <div class='clearfix'>
          <nav class="footer-nav navbar-expand-md navbar-light bg-none">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <%= link_to new_post_path, class:"btn footer-navbar-btn" do %> <span class="footer-nav-link" >New post </span><%end%>
                <%= link_to home_path, class:"btn footer-navbar-btn" do %> <span class="footer-nav-link" >Home </span><%end%>
                <%= link_to posts_path, class:"btn footer-navbar-btn" do %> <span class="footer-nav-link" >Posts </span><%end%>
              </div>
            </div>
          </nav>
        </div>
        <div class='clearfix'>
          <div class='social-networks'>
            <a class='socnet-btn btn social-network' href="#">Инстаграм</a>
            <a class='socnet-btn btn social-network' href="#">Фейсбук</a>
            <a class='socnet-btn btn social-network' href="#">Вконтакте</a>
          </div>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/pages/index.html.erb
<h1><%= @heading %></h1>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>